# PyTorch Baby Steps

In this notebook, I will explore basic PyTorch concepts

## Tensors

A **Tensor** is just a multidimensional array. PyTorch's tensors are like NumPy's `ndarray`s (which I have been using till now). But unlike `ndarray`s, PyTorch's **Tensors** can run on GPUs, or other hardware accelerators.

Tensors are at the CENTER of everything we do in PyTorch. For instance, the inputs, the outputs and even the learning weights of our deep learning models will stored in **Tensors**.

Let's get our hands dirty, and create some tensors.

Before starting with PyTorch, we must first import the `torch` module

In [1]:
import torch

In [2]:
t = torch.zeros(6, 3)
print(t)
print(t.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


We just created $6 \times 3$ matrix (i.e. tensor) filled with zeros. We printed its content, then printed the datatype. 

By default, PyTorch fills out tensors with 32-bit wide floating point numbers. But guess what?! We can change it. Here is how:

In [3]:
t = torch.zeros((6, 3), dtype=torch.int16)
print(t)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


We just created another $6 \times 3$ tensor, but this time, filled with `int` values. You will also notice that when printing this matrix, PyTorch printed the type to **remind us that we are not using the initial default datatype**.

Earlier, we told PyTorch that we want to create a tensor with `int` values. But it's just for *that* tensor. Meaning, if we create another tensor, PyTorch will use its default floating point `float32`.

What if we want PyTorch to work with `int` values or some other datatype. To acheive that we need to use PyTorch's [`set_default_type`](https://pytorch.org/docs/stable/generated/torch.set_default_dtype.html) to set its default datatype.

Remember when we were building the MLP? How did we first initialize the weights? **Randomly**. PyTorch also allows us to create tensors filled with random values. Here is a demo:

In [4]:
torch.manual_seed(1729)

r1 = torch.rand(2, 2)
print("A random 2x2 tensor:")
print(r1)

r2 = torch.rand(2, 2)
print("\nAnother random 2x2 tensor:")
print(r2)

A random 2x2 tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

Another random 2x2 tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])


# Matrix Operations

Tensors are multidimensional arrays (i.e. matrices). Consequently, we can also perform matrix operations with Tensors.

### Addition

We can add two tensors together using PyTorch's `add`

In [5]:
#Create two 1D tensors with values in [1,4)
a = torch.randint(1, 4, (2,))
b = torch.randint(1, 4, (2,))
print(a)
print(b)

#Added both "a" and "b" together and print result
c = torch.add(a, b)
print(c)

tensor([2, 3])
tensor([2, 2])
tensor([4, 5])


### Substraction

We can substract two tensors together using PyTorch's `substract` or `sub`

In [6]:
#Create two 1D tensors with values in [1, 4])
a = torch.randint(1, 4, (2,))
b = torch.randint(1, 4, (2,))
print(a)
print(b)

#Substracted both "a" and "b" together and print result
c = torch.subtract(a, b)
print(c)

tensor([3, 2])
tensor([2, 2])
tensor([1, 0])


### Scalar multiplication

We can multiply tensors with scalars using `*` operator or PyTorch's `mul`

In [7]:
#Create two 2x2 tensors with ones.
a = torch.ones((2, 2), dtype=torch.int16)
b = torch.ones((2, 2), dtype=torch.int16)

#Multiply both tensors with 2 and 3 respectively
print(a * 2)
print(torch.mul(b, 3))

tensor([[2, 2],
        [2, 2]], dtype=torch.int16)
tensor([[3, 3],
        [3, 3]], dtype=torch.int16)


### Matrix multiplication

We can multiply tensors together using PyTorch's `matmul`

In [8]:
a = torch.tensor([
    [2, 3],
    [1, -5]
])

b = torch.tensor([
    [4, 3, 6],
    [1, -2, 3]
])

ab = torch.matmul(a, b)
print(ab)

tensor([[11,  0, 21],
        [-1, 13, -9]])


# Other Mathematical Operations

PyTorch provides a suite of functions performing mathematical operations for our convenience. Among them are:

- `abs`: Returns absolute values of elements in tensors
- `det`: Computes the determinant of a tensor
- `max`: Returns the maximum value in a tensor
- `std_mean`: Compute both the standard deviation and average of a tensor
- etc.

There are much more to PyTorch that I can explain in this little notebook. So, the **Documentation is your BEST friend**